POST http://localhost:5000/feedback/feedback
content-type: application/json

{
    "guestID": 5,
        "feedbackDate": "2024-06-12T18:00:00",
        "feedbackDescription": "Enjoyed the amenities.",
        "rating": 4
}








# POST http://localhost:5000/hotel/hotel-information
# content-type: application/json

# {
#     "hotelName": "Urban Oasis",
#     "address": "222 Downtown Street",
#     "contactInformation": "555-7890",
#     "description": "City chic ",
#     "amenities": "Rooftop Bar, Fitness Center"
# }
# POST http://localhost:5000/roomType/room-types
# content-type: application/json

# {
#     "typeName": "Cottage",
#     "description": "Quaint cottage retreat",
#     "price": "120"
# }
# POST http://localhost:5000/room/rooms
# content-type: application/json

# {
#     "roomNumber": "402",
#     "roomTypeID": 3,
#     "status": "available"
# }
# POST http://localhost:5000/guest/guests
# content-type: application/json

# {
#     "firstName": "Michael",
#     "lastName": "Lee",
#     "address": "222 Cedar Drive",
#     "contactInformation": "555-5555",
#     "email": "michael@example.com",
#     "nationality": "France"
# }
# POST http://localhost:5000/reservation/reservations
# content-type: application/json

# {
#     "guestID": 6,
#     "roomID": 5,
#     "checkInDate": "2024-05-20",
#     "checkOutDate": "2024-05-25",
#     "totalPrice": "600",
#     "status": "confirmed"

# }
# POST http://localhost:5000/roomServiceOrder/room-service-orders
# content-type: application/json

# {
#    "roomID": 5,
#         "guestID": 5,
#         "orderDate": "2024-06-12",
#         "status": "pending"
# }
# POST http://localhost:5000/staff/staff
# content-type: application/json

# {
#     "firstName": "Emma",
#         "lastName": "Wilson",
#         "position": "Chef",
#         "contactInformation": "555-0000"
# }
# POST http://localhost:5000/feedback/feedback
# content-type: application/json

# {
#     "guestID": 5,
#         "feedbackDate": "2024-06-12T18:00:00",
#         "feedbackDescription": "Enjoyed the amenities.",
#         "rating": 4
# }




